const Quotes = [
    "1. Good morning, my love! Wishing you a day as bright and beautiful as your smile.",
    "2. Rise and shine, sweetheart! Another day to love you and make wonderful memories together.",
    "3. Good morning, sunshine! Your love is the best part of waking up.",
    "4. Wake up, sleepyhead! The world awaits, and so does my love for you.",
    "5. Good morning, love. May your day be filled with joy, laughter, and all the things that make you smile.",
    "6. Rise and shine, my love! Sending you a virtual hug to start your day with warmth and love.",
    "7. Good morning, sweetheart! Here's to a day filled with endless possibilities and our love growing stronger.",
    "8. Wake up, my love! Your presence in my life is a blessing, and I'm grateful for each morning with you.",
    "9. Good morning, sunshine! Today is a new chapter, and I'm excited to write it with you.",
    "10. Rise and shine, love of my life! Your love is the motivation behind every success and happiness in my day.",
    "11. Good morning, my love. As the sun rises, so does my love for you.",
    "12. Wake up with a smile, darling! Your happiness is my priority, and I hope today brings you immense joy.",
    "13. Good morning, my angel. You're the reason my mornings are filled with love and positivity.",
    "14. Rise and shine, love! Today is a canvas, and I can't wait to paint it with the colors of our love.",
    "15. Good morning, my heart. Your love is the melody that plays in the background of my day.",
    "16. Wake up, my love! Your presence makes every morning brighter and every moment more beautiful.",
    "17. Good morning, sunshine! Thank you for being the light in my life and making every day special.",
    "18. Rise and shine, sweetheart. Your love is the energy that powers my day.",
    "19. Good morning, love. Today is another opportunity to cherish and celebrate our beautiful connection.",
    "20. Wake up with a grateful heart, my love. I'm grateful for you every morning and every moment.",
    "21. Good morning, my love. May your day be as amazing as the love we share.",
    "22. Rise and shine, my joy. Your laughter is the sweetest melody, and I hope it echoes throughout your day.",
    "23. Good morning, my love. Sending you a virtual kiss to start your day with sweetness.",
    "24. Wake up, my love! Your presence is my favorite part of the morning.",
    "25. Good morning, sweetheart. Today is a new chance to create unforgettable memories together.",
    "26. Rise and shine, love of my life! Your love is the fuel for all my dreams and aspirations.",
    "27. Good morning, sunshine! I hope your day is as radiant as your beautiful smile.",
    "28. Wake up, my joy. Your love is the source of my happiness, and I can't wait to share another day with you.",
    "29. Good morning, my heart. Your love is the reason I wake up with gratitude every day.",
    "30. Rise and shine, my love. Your presence turns ordinary mornings into extraordinary moments.",
    "31. Good morning, love. May your day be filled with love, laughter, and all the things that make you happy.",
    "32. Wake up, my joy. Your love is the motivation that fuels my every action.",
    "33. Good morning, sunshine. Another day to love you more and create beautiful moments together.",
    "34. Rise and shine, sweetheart! Your love is the inspiration behind all my actions and accomplishments.",
    "35. Good morning, my angel. Your love is the guiding star in the journey of my life.",
    "36. Wake up, my heart. Your presence is my favorite part of every morning.",
    "37. Good morning, my love. Today is another chapter in our love story, and I'm excited to write it with you.",
    "38. Rise and shine, love! Another day to create beautiful memories and cherish the love we have.",
    "39. Good morning, my heart. Your love is the anchor that keeps me grounded and the wings that let me soar.",
    "40. Wake up, my love! Today is a gift, and I'm grateful to spend it with you.",
    "41. Good morning, sweetheart. Your love is the potion that transforms ordinary moments into magical memories.",
    "42. Rise and shine, my love. Your presence makes every morning a celebration of love and happiness.",
    "43. Good morning, sunshine! Your love is the melody that plays in my heart, creating a beautiful symphony.",
    "44. Wake up, my joy. Your laughter is the sweetest sound, and I hope it fills your day with happiness.",
    "45. Good morning, my love. Today is another opportunity to experience the magic of our love.",
    "46. Rise and shine, love of my life! Your love is the inspiration that propels me towards greatness.",
    "47. Good morning, my angel. Your love is the sunshine that brightens even the cloudiest days.",
    "48. Wake up, my heart! Your presence is the greatest gift, and I'm thankful for it every morning.",
    "49. Good morning, my love. May your day be filled with love, laughter, and all the things that make you happy.",
    "50. Rise and shine, my joy. Your love is the motivation that fuels my every action.",
    "51. Good morning, sunshine. Another day to love you more and make our journey together even more beautiful.",
    "52. Wake up, my love! Your love is the guiding light that leads me through every moment of the day.",
    "53. Good morning, sweetheart. With you, every day is an adventure, and I can't wait to explore it together.",
    "54. Rise and shine, love of my life. Your love is the strength that empowers me to overcome any challenge.",
    "55. Good morning, my heart. Your love is the masterpiece that colors every moment of my life.",
    "56. Wake up, my love. Today is another opportunity to fall in love with you all over again.",
    "57. Good morning, my angel. Your love is the sweetest melody, and I'm grateful to wake up to it every day.",
    "58. Rise and shine, my joy. Your presence is the greatest gift, and I cherish it every morning.",
    "59. Good morning, my love. May your day be as wonderful as the love we share.",
    "60. Wake up, my heart. Your love is the motivation that propels me towards a day of success and happiness.",
    "61. Good morning, sunshine. Another day to love you more and make our journey together even more beautiful.",
    "62. Rise and shine, love of my life. Your love is the strength that empowers me to overcome any challenge.",
    "63. Good morning, my angel. Your love is the masterpiece that colors every moment of my life.",
    "64. Wake up, my love. Today is another opportunity to fall in love with you all over again.",
    "65. Good morning, my heart. Your love is the melody that plays in the background of my day.",
    "66. Rise and shine, love of my life. Your presence makes every morning brighter and every moment more beautiful.",
    "67. Good morning, sunshine! Thank you for being the light in my life and making every day special.",
    "68. Wake up, sweetheart. Your love is the energy that powers my day with positivity and joy.",
    "69. Good morning, love. Today is another opportunity to cherish and celebrate our beautiful connection.",
    "70. Rise and shine, love of my life. Your love is the anchor that keeps me steady in the journey of life.",
    "71. Good morning, my angel. Your love is the light that brightens my darkest moments.",
    "72. Wake up, my love! Today is another opportunity to create love-filled memories together.",
    "73. Good morning, sweetheart. Your love is the sweetest melody, and I'm grateful to wake up to it every day.",
    "74. Rise and shine, my joy. Your presence is the greatest gift, and I cherish it every morning.",
    "75. Good morning, my love. May your day be as wonderful as the love we share.",
    "76. Wake up, my heart. Your love is the motivation that propels me towards a day of success and happiness.",
    "77. Good morning, sunshine. Another day to love you more and make our journey together even more beautiful.",
    "78. Rise and shine, love of my life. Your love is the strength that empowers me to overcome any challenge.",
    "79. Good morning, my angel. Your love is the masterpiece that colors every moment of my life.",
    "80. Wake up, my love. Today is another opportunity to fall in love with you all over again.",
    "81. Good morning, my heart. Your love is the melody that plays in the soundtrack of my life.",
    "82. Rise and shine, love of my life. Your presence makes every morning a blessing.",
    "83. Good morning, my angel. Your love is the compass that guides me through every day.",
    "84. Wake up, my love! Your smile is the sunrise that brightens my world.",
    "85. Good morning, sweetheart. Another day to cherish our love and create beautiful memories.",
    "86. Rise and shine, my joy. Your love is the warmth that makes every morning special.",
    "87. Good morning, my love. Today is a canvas, and I'm excited to paint it with the colors of our love.",
    "88. Wake up, sunshine! Your love is the energy that powers my day with positivity and joy.",
    "89. Good morning, my heart. Your love is the inspiration behind all the beauty in my life.",
    "90. Rise and shine, love of my life. Your love is the anchor that keeps me steady in the journey of life.",
    "91. Good morning, my angel. Your love is the light that brightens my darkest moments.",
    "92. Wake up, my love! Today is another opportunity to create love-filled memories together.",
    "93. Good morning, sweetheart. Your love is the sweetest melody, and I'm grateful to wake up to it every day.",
    "94. Rise and shine, my joy. Your presence is the greatest gift, and I cherish it every morning.",
    "95. Good morning, my love. May your day be as wonderful as the love we share.",
    "96. Wake up, my heart. Your love is the motivation that propels me towards a day of success and happiness.",
    "97. Good morning, sunshine. Another day to love you more and make our journey together even more beautiful.",
    "98. Rise and shine, love of my life. Your love is the strength that empowers me to overcome any challenge.",
    "99. Good morning, my angel. Your love is the masterpiece that colors every moment of my life.",
    "100. Wake up, my love. Today is another opportunity to fall in love with you all over again.",
    "101. I love you.",
    "102. I care about you.",
    "103. It's going to be hard, but it'll be worth it",
    "104. You are my everything.",
    "105. Don’t let anyone make you feel small or less worthy because they haven’t been in your shoes.",
    "106. You will find your peace.",
    "107. Good morning sunshine! Today is a new day to love and to succeed.",
    "108. Why is it always Good morning and not - 'Jab tak teri neend na tute, ugta nahi hai sooraj mera' :)",
    "109. I hope you find what you're actually looking for.",
    "110. It wasn't love at first sight. It took a full five minutes.",
    "111. Love is a two-way street constantly under construction.",
    "112. At the touch of love everyone becomes a poet.",
    "113. Love is sharing your chocolate",
    "114. I'm in lesbians with you",
    "115. There is no remedy for love, but to love more.",
    "116. All, everything that I understand, I understand only because I love.",
    "117. There's only one thing that cuts through all our realities and that's love",
    "118. Love is absence of judgement",
    "119. Love is a gift of one's inner most soul to another so both can be whole.",
    "120. The way is not in the sky. The way is in the heart.",
    "121. If I loved you less, I might be able to talk about it more.",
    "122. You had me at 'hello.'",
    "123. Call me by your name, and I'll call you by mine.",
    "124. It seems right now that all I've ever done in my life is making my way here to you.",
    "125. I wish I had done everything on earth with you.",
    "126. I've come here with no expectations, only to profess, now that I am at liberty to do so, that my heart is, and always will be, yours.",
    "127. It's like in that moment the whole universe existed just to bring us together.",
    "128. I do love nothing in the world so well as you.",
    "129. Love looks not with the eyes but with the mind.",
    "130. Love comforts like sunshine after rain.",
    "131. I love you with so much of my heart that none is left to protest.",
    "132. My dream wouldn't be complete without you in it.",
    "133. Some people are worth melting for.",
    "134. I look at you, and I'm home.",
    "135. It's enough for this restless wanderer just to be with you.",
    "136. All at once everything looks different, now that I see you.",
    "137. Love is a song that never ends.",
    "138. You mean more to me than anyone in this whole world.",
    "139. You are my greatest adventure.",
    "140. One song, my heart keeps singing, of one love only for you.",
    "141. I'd rather die tomorrow than live a hundred years without knowing you.",
    "142. Yes, you'll be in my heart. From this day on, now and forever more.",
    "143. So this is love. So this is what makes life divine.",
    "144. Love is an open door.",
    "145. Each happy ending's a brand new beginning.",
    "146. Any day spent with you is my favorite day.",
    "147. People always do crazy things when they're in love.",
    "148. For it is plain as anyone can see, we're simply meant to be.",
    "149. To face the future with another, who means more than any other, is to be loved.",
    "150. And if you ever forget how much you really mean to me, every day I will remind you.",
    "151. Now everybody asks me why I'm smiling out from ear to ear.",
    "152. Isn't it just so pretty to think all along there was some invisible string tying you to me?",
    "153. Be a best friend, tell the truth and overuse 'I love you.'",
    "154. You are my one in eight billion.",
    "155. Maybe you don't need the whole world to love you, you know. Maybe you just need one person.",
    "156. When you're a kid, you assume your parents are soulmates. My kids are gonna be right about that.",
    "157. You know you're in love when you can't fall asleep because reality is finally better than your dreams",
    "158. I hope it's okay if I love you forever.",
    "159. If you were in an accident, I wouldn't stop for red lights.",
    "160. To me you are perfect.",
    "161. It doesn't make you weak to love someone.",
    "162. May it be alright if my love for you lasts an eternity.",
    "163. Nobody has ever measured, not even poets, how much the heart can hold.",
    "164. For small creatures such as we, the vastness is bearable only through love.",
    "165. I would rather share one lifetime with you than face all the ages of this world alone.",
    "166. Thinking of you keeps me awake. Dreaming of you keeps me asleep. Being with you keeps me alive.",
    "167. Loved you yesterday, love you still, always have, always will.",
    "168. I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.",
    "169. In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
    "170. I’ll be loving you, always with a love that’s true.",
    "171. I need you like a heart needs a beat.",
    "172. You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.",
    "173. Love is like the wind, you can’t see it but you can feel it.",
    "174. Love is the magician that pulls man out of his own hat.",
    "175. Life is what happens when you're busy making other plans.",
    "176. Your time is limited, don't waste it living someone else's life.",
    "177. The only person you are destined to become is the person you decide to be.",
    "178. Success is stumbling from failure to failure with no loss of enthusiasm.",
    "179. The only limit to our realization of tomorrow will be our doubts of today.",
    "180. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "181. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "182. Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "183. The best revenge is massive success.",
    "184. You don't have to be great to start, but you have to start to be great.",
    "185. Success usually comes to those who are too busy to be looking for it.",
    "186. Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "187. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "188. Embrace the boundless possibilities of tomorrow, casting aside any lingering doubts of today.",
    "189. Embrace your inner strength and the vast potential within; it surpasses any obstacle.",
    "190. The future belongs to those who believe in the beauty of their dreams.",
    "191. The only person you are destined to become is the person you decide to be.",
    "192. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "193. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "194. Achieving massive success is the sweetest form of retaliation.",
    "195. Commencement may not demand greatness, but initiation is essential for greatness.",
    "196. Embrace your inner strength and the vast potential within; it surpasses any obstacle.",
    "197. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "198. Success usually comes to those who are too busy to be looking for it.",
    "199. The only way to achieve the impossible is to believe it is possible.",
    "200. Act as if what you do makes a difference. It does.",
    "201. Life unfolds amidst our plans and schemes.",
    "202. Your time is a limited resource; spend it crafting your unique narrative, not someone else's.",
    "203. Shape your destiny; become the person you aspire to be.",
    "204. Success is stumbling from failure to failure with no loss of enthusiasm.",
    "205. The only limit to our realization of tomorrow will be our doubts of today.",
    "206. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "207. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "208. Genuine happiness is the true measure of success; pursue what you love relentlessly.",
    "209. The best revenge is massive success.",
    "210. You don't have to be great to start, but you have to start to be great.",
    "211. Success usually comes to those who are too busy to be looking for it.",
    "212. Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "213. Life's allure lies in overcoming challenges, turning them into the essence of a meaningful existence.",
    "214. Seek tomorrow's potential unburdened by the doubts lingering today.",
    "215. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "216. The future belongs to those who believe in the beauty of their dreams.",
    "217. The only person you are destined to become is the person you decide to be.",
    "218. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "219. 219. Triumph isn't final, failure isn't fatal: it's the unwavering courage to persist that truly matters.",
    "220. The best revenge is massive success.",
    "221. You don't have to be great to start, but you have to start to be great.",
    "222. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "223. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "224. Success typically favors those engrossed in their pursuits rather than actively seeking it.",
    "225. The only way to achieve the impossible is to believe it is possible.",
    "226. Act as if what you do makes a difference. It does.",
    "227. Life takes unexpected turns while we're occupied with other plans.",
    "228. Cherish the limited time you have; don't allow it to be dictated by someone else's expectations.",
    "229. Mold yourself into the person you wish to become.",
    "230. Success is stumbling from failure to failure with no loss of enthusiasm.",
    "231. The only limit to our realization of tomorrow will be our doubts of today.",
    "232. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "233. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "234. True success stems from happiness, not the other way around; love what you do.",
    "235. The best revenge is massive success.",
    "236. You don't have to be great to start, but you have to start to be great.",
    "237. Success usually comes to those who are too busy to be looking for it.",
    "238. Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "239. Life gains meaning through conquering challenges rather than avoiding them.",
    "240. Let go of doubts today to fully realize the potential of tomorrow.",
    "241. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "242. The future belongs to those who believe in the beauty of their dreams.",
    "243. The only person you are destined to become is the person you decide to be.",
    "244. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "245. Triumph isn't final, failure isn't fatal: it's the unwavering courage to persist that truly matters.",
    "246. The best revenge is massive success.",
    "247. You don't have to be great to start, but you have to start to be great.",
    "248. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "249. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "250. Success often finds those fully immersed in their pursuits, not actively seeking it.",
    "251. The only way to achieve the impossible is to believe it is possible.",
    "252. Act as if what you do makes a difference. It does.",
    "253. Life takes unexpected turns while we're occupied with other plans.",
    "254. Cherish the limited time you have; don't allow it to be dictated by someone else's expectations.",
    "255. Mold yourself into the person you wish to become.",
    "256. Success is stumbling from failure to failure with no loss of enthusiasm.",
    "257. The only limit to our realization of tomorrow will be our doubts of today.",
    "258. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "259. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "260. Triumph isn't final, failure isn't fatal: it's the unwavering courage to persist that truly matters.",
    "261. The best revenge is massive success.",
    "262. You don't have to be great to start, but you have to start to be great.",
    "263. Success usually comes to those who are too busy to be looking for it.",
    "264. Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "265. Life gains meaning through conquering challenges rather than avoiding them.",
    "266. Let go of doubts today to fully realize the potential of tomorrow.",
    "267. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "268. The future belongs to those who believe in the beauty of their dreams.",
    "269. The only person you are destined to become is the person you decide to be.",
    "270. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "271. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "272. The best revenge is massive success.",
    "273. You don't have to be great to start, but you have to start to be great.",
    "274. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "275. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "276. Success often finds those fully immersed in their pursuits, not actively seeking it.",
    "277. The only way to achieve the impossible is to believe it is possible.",
    "278. Act as if what you do makes a difference. It does.",
    "279. Life takes unexpected turns while we're occupied with other plans.",
    "280. Cherish the limited time you have; don't allow it to be dictated by someone else's expectations.",
    "281. Mold yourself into the person you wish to become.",
    "282. Success is stumbling from failure to failure with no loss of enthusiasm.",
    "283. The only limit to our realization of tomorrow will be our doubts of today.",
    "284. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "285. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "286. Triumph isn't final, failure isn't fatal: it's the unwavering courage to persist that truly matters.",
    "287. The best revenge is massive success.",
    "288. You don't have to be great to start, but you have to start to be great.",
    "289. Success usually comes to those who are too busy to be looking for it.",
    "290. Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "291. Life gains meaning through conquering challenges rather than avoiding them.",
    "292. Let go of doubts today to fully realize the potential of tomorrow.",
    "293. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "294. The future belongs to those who believe in the beauty of their dreams.",
    "295. The only person you are destined to become is the person you decide to be.",
    "296. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "297. Triumph isn't final, failure isn't fatal: it's the unwavering courage to persist that truly matters.",
    "298. The best revenge is massive success.",
    "299. Commencement may not demand greatness, but initiation is essential for greatness.",
    "300. Embrace your inner strength and the vast potential within; it surpasses any obstacle.",
    "301. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "302. Success usually comes to those who are too busy to be looking for it.",
    "303. The only way to achieve the impossible is to believe it is possible.",
    "304. Act as if what you do makes a difference. It does.",

    "305. Your time is limited, don't waste it living someone else's life.",
    "306. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "307. In three words, I can sum up everything I've learned about life: it goes on.",
    "308. The only way to do great work is to love what you do.",
    "309. You are never too old to set another goal or to dream a new dream.",
    "310. The only limit to our realization of tomorrow will be our doubts of today.",
    "311. Don't wait to strike till the iron is hot, but make it hot by striking.",

    "312. The only way to achieve the impossible is to believe it is possible.",
    "313. Act as if what you do makes a difference. It does.",
    "314. Life is what happens when you're busy making other plans.",
    "315. Your time is limited, don't waste it living someone else's life.",
    "316. Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "317. The best revenge is massive success.",
    "318. You don't have to be great to start, but you have to start to be great.",
    "319. Success usually comes to those who are too busy to be looking for it.",
    "320. Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "321. The only person you are destined to become is the person you decide to be.",
    "322. In three words, I can sum up everything I've learned about life: it goes on.",
    "323. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "324. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "325. The future belongs to those who believe in the beauty of their dreams.",
    "326. The only limit to our realization of tomorrow will be our doubts of today.",
    "327. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "328. Believe you can, and you're halfway there.",
    "329. Your time is limited, don't waste it living someone else's life.",
    "330. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "331. In three words, I can sum up everything I've learned about life: it goes on.",
    "332. The only person you are destined to become is the person you decide to be.",
    "333. Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "334. Believe you can, and you're halfway there.",
    "335. Your time is limited, don't waste it living someone else's life.",
    "336. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "337. In three words, I can sum up everything I've learned about life: it goes on.",
    "338. The only way to do great work is to love what you do.",
    "339. You are never too old to set another goal or to dream a new dream.",
    "340. The only limit to our realization of tomorrow will be our doubts of today.",
    "341. Don't wait to strike till the iron is hot, but make it hot by striking.",
    "342. The only way to achieve the impossible is to believe it is possible.",
    "343. Act as if what you do makes a difference. It does.",
    "344. Life is what happens when you're busy making other plans.",
    "345. Your time is limited, don't waste it living someone else's life.",
    "346. Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "347. The best revenge is massive success.",
    "348. You don't have to be great to start, but you have to start to be great.",
    "349. Success usually comes to those who are too busy to be looking for it.",
    "350. Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "351. The only person you are destined to become is the person you decide to be.",
    "352. In three words, I can sum up everything I've learned about life: it goes on.",
    "353. Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "354. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "355. The future belongs to those who believe in the beauty of their dreams.",
    "356. The only limit to our realization of tomorrow will be our doubts of today.",
    "357. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "358. Believe you can, and you're halfway there.",
    "359. Your time is limited, don't waste it living someone else's life.",
    "360. Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "361. In three words, I can sum up everything I've learned about life: it goes on.",
    "362. The only person you are destined to become is the person you decide to be.",
    "363. Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "364. Believe you can, and you're halfway there.",
    "365. Your time is limited, don't waste it living someone else's life.",
];

export default Quotes;
